on:
    push:
        branches:
            - main

name: release-please

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: GoogleCloudPlatform/release-please-action@v3
              id: release
              with:
                  release-type: node
                  command: manifest
                  token: ${{secrets.GITHUB_TOKEN}}
                  default-branch: main

            # Output which releases were created
            - run: echo "A release was created."
              if: ${{ steps.release.outputs.releases_created }}

            # Check to see if we need to do any releases and if so check out the repo
            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.releases_created }}

            # Node.js release
            - uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.releases_created }}
              with:
                  node-version: lts/*
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
              if: ${{ steps.release.outputs.releases_created }}

            - name: Publish @humanfs/core package to npm
              run: npm publish -w packages/core
              if: ${{ steps.release.outputs['packages/core--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/node package to npm
              run: npm publish -w packages/node
              if: ${{ steps.release.outputs['packages/node--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/deno package to npm
              run: npm publish -w packages/deno
              if: ${{ steps.release.outputs['packages/deno--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/memory package to npm
              run: npm publish -w packages/memory
              if: ${{ steps.release.outputs['packages/memory--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/web package to npm
              run: npm publish -w packages/web
              if: ${{ steps.release.outputs['packages/web--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/types package to npm
              run: npm publish -w packages/types
              if: ${{ steps.release.outputs['packages/types--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - name: Publish @humanfs/test package to npm
              run: npm publish -w packages/test
              if: ${{ steps.release.outputs['packages/test--release_created'] }}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
